name: d3pm
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pip:
      - torch
      - torchvision
      - pillow
      - tqdm
      - wandb
      - datasets
      - transformers
      - deepspeed
      - click
