name: d3pm
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch==2.2.*
  - torchvision==0.17.*
  - pytorch-cuda=12.1
  - pip
  - pip:
      - pillow
      - tqdm
      - wandb
      - datasets
      - transformers
      - deepspeed
      - click
